openapi: 3.0.3
info:
  title: FinishIT
  description: REST Documentation for Finish IT backend
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /api/auth: {}

  /api/register: {}

  /api/user:
    get:
      summary: "GET api/user"
      operationId: "getUser"
      responses:
        "200":
          description: "OK"
    put:
      summary: "PUT api/user"
      operationId: "updateUser"
      responses:
        "200":
          description: "OK"
    delete:
      summary: "DELETE api/user"
      operationId: "deleteUser"
      responses:
        "200":
          description: "OK"

  /api/doc:
    get:
      summary: "GET api/doc"
      operationId: "getDocs"
      responses:
        "200":
          description: "OK"
    post:
      summary: "POST api/doc"
      operationId: "addDoc"
      responses:
        "200":
          description: "OK"

  /api/doc/{id}:
    get:
      summary: "GET api/doc/{id}"
      operationId: "getDoc"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
    put:
      summary: "PUT api/doc/{id}"
      operationId: "updateDoc"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
    delete:
      summary: "DELETE api/doc/{id}"
      operationId: "deleteDoc"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"

  /api/doc/{id}/comment:
    post:
      summary: "POST api/doc/{id}/comment"
      operationId: "addComment"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"

  /api/doc/{id}/comment/{commentId}:
    put:
      summary: "PUT api/doc/{id}/comment/{commentId}"
      operationId: "updateComment"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "commentId"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
    delete:
      summary: "DELETE api/doc/{id}/comment/{commentId}"
      operationId: "deleteComment"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "commentId"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"

  /api/doc/{id}/task:
    post:
      summary: "POST api/doc/{id}/task"
      operationId: "addTask"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"

  /api/doc/{id}/task/{taskId}:
    put:
      summary: "PUT api/doc/{id}/task/{taskId}"
      operationId: "updateTask"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "taskId"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
    delete:
      summary: "DELETE api/doc/{id}/task/{taskId}"
      operationId: "deleteTask"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "taskId"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"

  /api/doc/{id}/task/{taskId}/do:
    put:
      summary: "PUT api/doc/{id}/task/{taskId}/do"
      operationId: "markTaskDone"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "taskId"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"

  /api/doc/{id}/task/{taskId}/undo:
    put:
      summary: "PUT api/doc/{id}/task/{taskId}/undo"
      operationId: "markTaskNotDone"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "taskId"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"

  /api/doc/{id}/users:
    post:
      summary: "POST api/doc/{id}/users"
      operationId: "addUser"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"

  /api/doc/{id}/users/{userId}:
    delete:
      summary: "DELETE api/doc/{id}/users/{userId}"
      operationId: "deleteUser"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "userId"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"